name: CI/CD Pipeline para Previsão do Preço do Bitcoin

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite (UTC)

jobs:
  train-bitcoin-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências e DVC
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Testes Unitários
        run: |
          pytest tests/

      - name: Executar Pipeline de Dados e Treinamento
        run: |
          dvc repro -f # Executa todas as etapas do pipeline definido no dvc.yaml

      - name: Salvar Atualizações no DVC e Git
        run: |
          dvc push  # Envia os novos arquivos versionados (ex.: modelo treinado)
          git add .
          git commit -m "Atualizando DVC com novos artefatos" || echo "Nada para commitar"
          git push || echo "Nada para enviar"