name: CI/CD Pipeline para Previsão do Preço do Bitcoin

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite (UTC)

jobs:
  train-bitcoin-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências e DVC
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Definir PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/mlops:$PYTHONPATH" >> $GITHUB_ENV


      - name: Executar Testes Unitários
        run: |
          pytest tests/